[package]
name = "waiting-pgrep"
version = "1.0.0"
authors = ["Jacob Karlsson <jacob.karlsson95@gmail.com>"]
description = "Sort of like pgrep, but if it can't find the process directly, it waits until it does"

[dependencies]
clap = "2.32.0"
psutil = "1.1.1"
